image: registry.gitlab.com/famedly/company/frontend/flutter-dockerimages/flutter/stable

stages:
  - test

code_analyze:
  tags:
    - docker
  stage: test
  script:
    - flutter pub get
    - flutter format --set-exit-if-changed lib/ test/
    - flutter analyze
